language: generic

services:
  - docker

env:
  matrix:
    - OS=centos DIST=7 PHPV="PHP 5.6.33"
    - OS=ubuntu DIST=14.04 PHPV="PHP 5.6.33"
    - OS=ubuntu DIST=16.04 PHPV="PHP 5.6.33"
    - OS=ubuntu DIST=17.10 PHPV="PHP 5.6.33"
    - OS=debian DIST=8 PHPV="PHP 5.6.33"
    - OS="rockyluke/devuan" DIST=1 PHPV="PHP 5.6.33"
    
    - OS=centos DIST=7 PHPV="PHP 7.0.27"
    - OS=ubuntu DIST=14.04 PHPV="PHP 7.0.27"
    - OS=ubuntu DIST=16.04 PHPV="PHP 7.0.27"
    - OS=ubuntu DIST=17.10 PHPV="PHP 7.0.27"
    - OS=debian DIST=8 PHPV="PHP 7.0.27"
    - OS=debian DIST=9 PHPV="PHP 7.0.27"
    - OS="rockyluke/devuan" DIST=1 PHPV="PHP 7.0.27"
    
    - OS=centos DIST=7 PHPV="PHP 7.1.14"
    - OS=ubuntu DIST=14.04 PHPV="PHP 7.1.14"
    - OS=ubuntu DIST=16.04 PHPV="PHP 7.1.14"
    - OS=ubuntu DIST=17.10 PHPV="PHP 7.1.14"
    - OS=debian DIST=8 PHPV="PHP 7.1.14"
    - OS=debian DIST=9 PHPV="PHP 7.1.14"
    - OS="rockyluke/devuan" DIST=1 PHPV="PHP 7.1.14"
    
    - OS=centos DIST=7 PHPV="PHP 7.2.2"
    - OS=ubuntu DIST=14.04 PHPV="PHP 7.2.2"
    - OS=ubuntu DIST=16.04 PHPV="PHP 7.2.2"
    - OS=ubuntu DIST=17.10 PHPV="PHP 7.2.2"
    - OS=debian DIST=8 PHPV="PHP 7.2.2"
    - OS=debian DIST=9 PHPV="PHP 7.2.2"
    - OS="rockyluke/devuan" DIST=1 PHPV="PHP 7.2.2"
    
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
    
script:
  - shellcheck versions.sh
  - shellcheck php-compiler.sh
  - sed -e "s:&&OS&&:${OS}:g" ./Dockerfile.sample | sed -e "s:&&DIST&&:${DIST}:g" | sed -e "s:&&PHPVL&&:${PHPV}:g" | sed -e "s:&&PHPVS&&:php${PHPV:4:1}${PHPV:6:1}:g" | tee Dockerfile
  - docker build -t sergix44/ispc-phpcompiler .
