language: generic

services:
  - docker

env:
  matrix:
    # OS=centos DIST=7 PHPV="PHP 5.6.32"
    # OS=ubuntu DIST=14.04 PHPV="PHP 5.6.32"
    - OS=ubuntu DIST=16.04 PHPV="PHP 5.6.32"
    # OS=ubuntu DIST=17.04 PHPV="PHP 5.6.32"
    # OS=debian DIST=7 PHPV="PHP 5.6.32"
    - OS=debian DIST=8 PHPV="PHP 5.6.32"
    - OS=debian DIST=9 PHPV="PHP 5.6.32"

    # OS=centos DIST=7 PHPV="PHP 7.0.26"
    # OS=ubuntu DIST=14.04 PHPV="PHP 7.0.26"
    - OS=ubuntu DIST=16.04 PHPV="PHP 7.0.26"
    # OS=ubuntu DIST=17.04 PHPV="PHP 7.0.26"
    # OS=debian DIST=7 PHPV="PHP 7.0.26"
    - OS=debian DIST=8 PHPV="PHP 7.0.26"
    - OS=debian DIST=9 PHPV="PHP 7.0.26"

    # OS=centos DIST=7 PHPV="PHP 7.1.12"
    # OS=ubuntu DIST=14.04 PHPV="PHP 7.1.12"
    - OS=ubuntu DIST=16.04 PHPV="PHP 7.1.12"
    # OS=ubuntu DIST=17.04 PHPV="PHP 7.1.12"
    # OS=debian DIST=7 PHPV="PHP 7.1.12"
    - OS=debian DIST=8 PHPV="PHP 7.1.12"
    - OS=debian DIST=9 PHPV="PHP 7.1.12"

    # OS=centos DIST=7 PHPV="PHP 7.2.0"
    # OS=ubuntu DIST=14.04 PHPV="PHP 7.2.0"
    - OS=ubuntu DIST=16.04 PHPV="PHP 7.2.0"
    # OS=ubuntu DIST=17.04 PHPV="PHP 7.2.0"
    # OS=debian DIST=7 PHPV="PHP 7.2.0"
    - OS=debian DIST=8 PHPV="PHP 7.2.0"
    - OS=debian DIST=9 PHPV="PHP 7.2.0"

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
    
script:
  - shellcheck versions.sh
  - shellcheck php-compiler.sh
  - sed -e "s/&&OS&&/${OS}/g" ./Dockerfile.sample | \
    sed -e "s/&&DIST&&/${DIST}/g" | \
    sed -e "s/&&PHPVL&&/${PHPV}/g" | \
    sed -e "s/&&PHPVS&&/php${PHPV:4:1}${PHPV:6:1}/g" | \
    tee Dockerfile
  - docker build -t pe46dro/ispc-php .
