language: generic

services:
  - docker

env:
  matrix:
    - OS=centos DIST=7 PHPV="PHP 5.6.36"
    - OS=ubuntu DIST=14.04 PHPV="PHP 5.6.36"
    - OS=ubuntu DIST=16.04 PHPV="PHP 5.6.36"
    - OS=ubuntu DIST=17.10 PHPV="PHP 5.6.36"
    - OS=debian DIST=8 PHPV="PHP 5.6.36"
    - OS="rockyluke/devuan" DIST=1 PHPV="PHP 5.6.36"
    
    - OS=centos DIST=7 PHPV="PHP 7.0.30"
    - OS=ubuntu DIST=14.04 PHPV="PHP 7.0.30"
    - OS=ubuntu DIST=16.04 PHPV="PHP 7.0.30"
    - OS=ubuntu DIST=17.10 PHPV="PHP 7.0.30"
    - OS=debian DIST=8 PHPV="PHP 7.0.30"
    - OS=debian DIST=9 PHPV="PHP 7.0.30"
    - OS="rockyluke/devuan" DIST=1 PHPV="PHP 7.0.30"
    
    - OS=centos DIST=7 PHPV="PHP 7.1.17"
    - OS=ubuntu DIST=14.04 PHPV="PHP 7.1.17"
    - OS=ubuntu DIST=16.04 PHPV="PHP 7.1.17"
    - OS=ubuntu DIST=17.10 PHPV="PHP 7.1.17"
    - OS=debian DIST=8 PHPV="PHP 7.1.17"
    - OS=debian DIST=9 PHPV="PHP 7.1.17"
    - OS="rockyluke/devuan" DIST=1 PHPV="PHP 7.1.17"
    
    - OS=centos DIST=7 PHPV="PHP 7.2.5"
    - OS=ubuntu DIST=14.04 PHPV="PHP 7.2.5"
    - OS=ubuntu DIST=16.04 PHPV="PHP 7.2.5"
    - OS=ubuntu DIST=17.10 PHPV="PHP 7.2.5"
    - OS=debian DIST=8 PHPV="PHP 7.2.5"
    - OS=debian DIST=9 PHPV="PHP 7.2.5"
    - OS="rockyluke/devuan" DIST=1 PHPV="PHP 7.2.5"
        
script:
  - shellcheck versions.sh
  - shellcheck php-compiler.sh
  - sed -e "s:&&OS&&:${OS}:g" ./Dockerfile.sample | sed -e "s:&&DIST&&:${DIST}:g" | sed -e "s:&&PHPVL&&:${PHPV}:g" | sed -e "s:&&PHPVS&&:php${PHPV:4:1}${PHPV:6:1}:g" | tee Dockerfile
  - docker build -t sergix44/ispc-phpcompiler .
