on: [push]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: ${{ matrix.os }} ${{ matrix.phpv }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["centos:7", "centos:8", "ubuntu:16.04", "ubuntu:18.04", "ubuntu:20.04", "debian:9", "debian:10", "rdebath\\/devuan:ascii"]
        phpv: ["PHP 5.6.40", "PHP 7.0.33", "PHP 7.1.33", "PHP 7.2.34", "PHP 7.3.23", "PHP 7.4.11"]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: shellcheck
        run: |
          sudo apt-get install -y shellcheck
          shellcheck versions.sh
          shellcheck -x php-compiler.sh
      - name: build
        run: |
          cat /proc/cpuinfo
          phpvs="${{ matrix.phpv }}"
          phpvs="php${phpvs:4:1}${phpvs:6:1}"
          echo ${{ matrix.os }}
          echo $phpvs
          sed -e "s/&&OS&&/${{ matrix.os }}/g" ./Dockerfile.actions | sed -e "s:&&PHPVL&&:${{ matrix.phpv }}:g" | sed -e "s:&&PHPVS&&:${phpvs}:g" | tee Dockerfile
          docker build -t sergix44/ispc-phpcompiler .
